'use strict';
const models = require('../models');
module.exports = (sequelize, DataTypes) => {
    const match = sequelize.define('match', {
        gameId: {
            type: DataTypes.INTEGER,
            allowNull: false,
        },
        summonerId: {
            type: DataTypes.INTEGER,
            allowNull: false,
        },
        accountId: {
            type: DataTypes.INTEGER,
            allowNull: false,
        },
        profileIcon: {
            type: DataTypes.INTEGER,
            allowNull: false
        },
        participantId: {
            type: DataTypes.INTEGER,
            allowNull: false
        },
        win:{
            type: DataTypes.STRING,
            allowNull: false
        },
        item0:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        item1:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        item2:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        item3:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        item4:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        item5:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        item6:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        deaths:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        kills:{
            type: DataTypes.INTEGER,
            allowNull: false
        },
        assists:{
            type: DataTypes.INTEGER,
            allowNull: false
        }
    });

    match.associate =  (models) => {
        match.belongsToMany(models.matchlist, {
            through: 'listM',
            unique: true
        });
    };

    return match;
};

// {
//     "seasonId": 11,
//     "queueId": 430,
//     "gameId": 567587094,
//     "participantIdentities": [
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "SKT T1 Deckline",
//                 "matchHistoryUri": "/v1/stats/player_history/NA1/42737717",
//                 "platformId": "NA1",
//                 "currentAccountId": 152564,
//                 "profileIcon": 3155,
//                 "summonerId": 147664,
//                 "accountId": 42737717
//             },
//             "participantId": 1
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "Raiin7",
//                 "matchHistoryUri": "/v1/stats/player_history/LA2/202642491",
//                 "platformId": "LA2",
//                 "currentAccountId": 202642491,
//                 "profileIcon": 1109,
//                 "summonerId": 7271106,
//                 "accountId": 202642491
//             },
//             "participantId": 2
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "Jurío Violento",
//                 "matchHistoryUri": "/v1/stats/player_history/LA2/200320840",
//                 "platformId": "LA2",
//                 "currentAccountId": 200320840,
//                 "profileIcon": 2099,
//                 "summonerId": 2823441,
//                 "accountId": 200320840
//             },
//             "participantId": 3
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "gatovier157",
//                 "matchHistoryUri": "/v1/stats/player_history/LA2/203702600",
//                 "platformId": "LA2",
//                 "currentAccountId": 203702600,
//                 "profileIcon": 3354,
//                 "summonerId": 10021843,
//                 "accountId": 203702600
//             },
//             "participantId": 4
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "benjitazx90",
//                 "matchHistoryUri": "/v1/stats/player_history/LA2/202076431",
//                 "platformId": "LA2",
//                 "currentAccountId": 202076431,
//                 "profileIcon": 3382,
//                 "summonerId": 6113089,
//                 "accountId": 202076431
//             },
//             "participantId": 5
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "Edge2G",
//                 "matchHistoryUri": "/v1/stats/player_history/NA1/47817395",
//                 "platformId": "NA1",
//                 "currentAccountId": 227307,
//                 "profileIcon": 3201,
//                 "summonerId": 222407,
//                 "accountId": 47817395
//             },
//             "participantId": 6
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "Aleeh",
//                 "matchHistoryUri": "/v1/stats/player_history/NA1/205009443",
//                 "platformId": "NA1",
//                 "currentAccountId": 128384,
//                 "profileIcon": 606,
//                 "summonerId": 123484,
//                 "accountId": 205009443
//             },
//             "participantId": 7
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "El Zoke Cheddar",
//                 "matchHistoryUri": "/v1/stats/player_history/LA2/1405834",
//                 "platformId": "LA2",
//                 "currentAccountId": 1405834,
//                 "profileIcon": 3382,
//                 "summonerId": 1285514,
//                 "accountId": 1405834
//             },
//             "participantId": 8
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "Orick",
//                 "matchHistoryUri": "/v1/stats/player_history/NA1/48736021",
//                 "platformId": "NA1",
//                 "currentAccountId": 118550,
//                 "profileIcon": 3379,
//                 "summonerId": 113649,
//                 "accountId": 48736021
//             },
//             "participantId": 9
//         },
//         {
//             "player": {
//                 "currentPlatformId": "LA2",
//                 "summonerName": "bunnys op",
//                 "matchHistoryUri": "/v1/stats/player_history/LA2/200394493",
//                 "platformId": "LA2",
//                 "currentAccountId": 200394493,
//                 "profileIcon": 713,
//                 "summonerId": 2801742,
//                 "accountId": 200394493
//             },
//             "participantId": 10
//         }
//     ],
//     "gameVersion": "8.7.223.9264",
//     "platformId": "LA2",
//     "gameMode": "CLASSIC",
//     "mapId": 11,
//     "gameType": "MATCHED_GAME",
//     "teams": [
//         {
//             "firstDragon": false,
//             "bans": [],
//             "firstInhibitor": false,
//             "win": "Fail",
//             "firstRiftHerald": false,
//             "firstBaron": false,
//             "baronKills": 0,
//             "riftHeraldKills": 0,
//             "firstBlood": false,
//             "teamId": 100,
//             "firstTower": true,
//             "vilemawKills": 0,
//             "inhibitorKills": 0,
//             "towerKills": 4,
//             "dominionVictoryScore": 0,
//             "dragonKills": 0
//         },
//         {
//             "firstDragon": true,
//             "bans": [],
//             "firstInhibitor": true,
//             "win": "Win",
//             "firstRiftHerald": true,
//             "firstBaron": true,
//             "baronKills": 1,
//             "riftHeraldKills": 1,
//             "firstBlood": true,
//             "teamId": 200,
//             "firstTower": false,
//             "vilemawKills": 0,
//             "inhibitorKills": 3,
//             "towerKills": 11,
//             "dominionVictoryScore": 0,
//             "dragonKills": 3
//         }
//     ],
//     "participants": [
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 5,
//                 "visionScore": 14,
//                 "magicDamageDealtToChampions": 2855,
//                 "largestMultiKill": 2,
//                 "totalTimeCrowdControlDealt": 176,
//                 "longestTimeSpentLiving": 830,
//                 "perk1Var1": 714,
//                 "perk1Var3": 0,
//                 "perk1Var2": 0,
//                 "tripleKills": 0,
//                 "perk5": 8237,
//                 "perk4": 8234,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 11,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 471,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 8,
//                 "damageDealtToTurrets": 6355,
//                 "physicalDamageDealtToChampions": 23843,
//                 "damageDealtToObjectives": 10811,
//                 "perk2Var2": 50,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 3,
//                 "perk2Var1": 12,
//                 "perk4Var1": 25,
//                 "totalDamageTaken": 20519,
//                 "perk4Var3": 0,
//                 "wardsKilled": 2,
//                 "largestCriticalStrike": 1047,
//                 "largestKillingSpree": 6,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 11577,
//                 "firstBloodAssist": false,
//                 "item2": 3140,
//                 "item3": 3094,
//                 "item0": 1053,
//                 "item1": 3009,
//                 "item6": 3340,
//                 "item4": 3087,
//                 "item5": 3031,
//                 "perk1": 9111,
//                 "perk0": 8021,
//                 "perk3": 8014,
//                 "perk2": 9104,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 459,
//                 "damageSelfMitigated": 9914,
//                 "magicalDamageTaken": 6901,
//                 "perk0Var2": 0,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 519,
//                 "assists": 8,
//                 "perk4Var2": 0,
//                 "goldSpent": 12300,
//                 "trueDamageDealt": 991,
//                 "participantId": 1,
//                 "physicalDamageDealt": 142403,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 26699,
//                 "physicalDamageTaken": 13098,
//                 "totalPlayerScore": 0,
//                 "win": false,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 154972,
//                 "neutralMinionsKilledEnemyJungle": 0,
//                 "deaths": 7,
//                 "wardsPlaced": 8,
//                 "perkPrimaryStyle": 8000,
//                 "perkSubStyle": 8200,
//                 "turretKills": 2,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 0,
//                 "goldEarned": 12929,
//                 "killingSprees": 2,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": true,
//                 "champLevel": 13,
//                 "doubleKills": 3,
//                 "inhibitorKills": 0,
//                 "firstInhibitorAssist": false,
//                 "perk0Var1": 3272,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 0,
//                 "visionWardsBoughtInGame": 0,
//                 "pentaKills": 0,
//                 "totalHeal": 5417,
//                 "totalMinionsKilled": 183,
//                 "timeCCingOthers": 21
//             },
//             "spell1Id": 4,
//             "participantId": 1,
//             "highestAchievedSeasonTier": "DIAMOND",
//             "spell2Id": 7,
//             "teamId": 100,
//             "timeline": {
//                 "lane": "BOTTOM",
//                 "participantId": 1,
//                 "csDiffPerMinDeltas": {
//                     "0-10": -0.25,
//                     "10-20": 0.34999999999999964
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 374.6,
//                     "10-20": 482.79999999999995
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": 59.7,
//                     "10-20": -7.149999999999977
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 6.300000000000001,
//                     "10-20": 6.8
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 346.7,
//                     "10-20": 421.8
//                 },
//                 "role": "DUO_CARRY",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": -50.89999999999998,
//                     "10-20": 192.10000000000005
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 346.6,
//                     "10-20": 682.0999999999999
//                 }
//             },
//             "championId": 202
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 8,
//                 "visionScore": 11,
//                 "magicDamageDealtToChampions": 460,
//                 "largestMultiKill": 1,
//                 "totalTimeCrowdControlDealt": 105,
//                 "longestTimeSpentLiving": 252,
//                 "perk1Var1": 291,
//                 "perk1Var3": 0,
//                 "perk1Var2": 0,
//                 "tripleKills": 0,
//                 "perk5": 8014,
//                 "perk4": 9111,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 4,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 215,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 12,
//                 "damageDealtToTurrets": 1646,
//                 "physicalDamageDealtToChampions": 10076,
//                 "damageDealtToObjectives": 1772,
//                 "perk2Var2": 0,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 1,
//                 "perk2Var1": 7,
//                 "perk4Var1": 419,
//                 "totalDamageTaken": 19951,
//                 "perk4Var3": 0,
//                 "wardsKilled": 0,
//                 "largestCriticalStrike": 0,
//                 "largestKillingSpree": 3,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 3907,
//                 "firstBloodAssist": false,
//                 "item2": 3155,
//                 "item3": 3071,
//                 "item0": 3147,
//                 "item1": 3111,
//                 "item6": 3340,
//                 "item4": 1036,
//                 "item5": 1036,
//                 "perk1": 8143,
//                 "perk0": 8112,
//                 "perk3": 8135,
//                 "perk2": 8138,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 5,
//                 "damageSelfMitigated": 12619,
//                 "magicalDamageTaken": 6412,
//                 "perk0Var2": 0,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 1838,
//                 "assists": 5,
//                 "perk4Var2": 0,
//                 "goldSpent": 9250,
//                 "trueDamageDealt": 5107,
//                 "participantId": 2,
//                 "physicalDamageDealt": 83115,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 11234,
//                 "physicalDamageTaken": 11700,
//                 "totalPlayerScore": 0,
//                 "win": false,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 92129,
//                 "neutralMinionsKilledEnemyJungle": 4,
//                 "deaths": 8,
//                 "wardsPlaced": 9,
//                 "perkPrimaryStyle": 8100,
//                 "perkSubStyle": 8000,
//                 "turretKills": 1,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 697,
//                 "goldEarned": 9440,
//                 "killingSprees": 1,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": false,
//                 "champLevel": 12,
//                 "doubleKills": 0,
//                 "inhibitorKills": 0,
//                 "firstInhibitorAssist": false,
//                 "perk0Var1": 873,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 0,
//                 "visionWardsBoughtInGame": 0,
//                 "pentaKills": 0,
//                 "totalHeal": 3142,
//                 "totalMinionsKilled": 133,
//                 "timeCCingOthers": 2
//             },
//             "spell1Id": 14,
//             "participantId": 2,
//             "highestAchievedSeasonTier": "PLATINUM",
//             "spell2Id": 4,
//             "teamId": 100,
//             "timeline": {
//                 "lane": "MIDDLE",
//                 "participantId": 2,
//                 "csDiffPerMinDeltas": {
//                     "0-10": -1.1000000000000005,
//                     "10-20": 1.0000000000000002
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 221.7,
//                     "10-20": 377.7
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": -177.20000000000002,
//                     "10-20": 19.80000000000001
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 5.8,
//                     "10-20": 5.6
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 321.9,
//                     "10-20": 397.3
//                 },
//                 "role": "SOLO",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": 103.90000000000002,
//                     "10-20": -34.400000000000006
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 486.1,
//                     "10-20": 548.7
//                 }
//             },
//             "championId": 238
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 68,
//                 "visionScore": 14,
//                 "magicDamageDealtToChampions": 5270,
//                 "largestMultiKill": 1,
//                 "totalTimeCrowdControlDealt": 512,
//                 "longestTimeSpentLiving": 434,
//                 "perk1Var1": 279,
//                 "perk1Var3": 0,
//                 "perk1Var2": 0,
//                 "tripleKills": 0,
//                 "perk5": 8236,
//                 "perk4": 8234,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 6,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 24,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 84,
//                 "damageDealtToTurrets": 338,
//                 "physicalDamageDealtToChampions": 6146,
//                 "damageDealtToObjectives": 338,
//                 "perk2Var2": 50,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 1,
//                 "perk2Var1": 12,
//                 "perk4Var1": 17,
//                 "totalDamageTaken": 24210,
//                 "perk4Var3": 0,
//                 "wardsKilled": 1,
//                 "largestCriticalStrike": 0,
//                 "largestKillingSpree": 2,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 27870,
//                 "firstBloodAssist": false,
//                 "item2": 3115,
//                 "item3": 0,
//                 "item0": 3146,
//                 "item1": 3111,
//                 "item6": 3340,
//                 "item4": 0,
//                 "item5": 3706,
//                 "perk1": 9111,
//                 "perk0": 8005,
//                 "perk3": 8299,
//                 "perk2": 9104,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 288,
//                 "damageSelfMitigated": 13793,
//                 "magicalDamageTaken": 7343,
//                 "perk0Var2": 667,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 873,
//                 "assists": 10,
//                 "perk4Var2": 0,
//                 "goldSpent": 8650,
//                 "trueDamageDealt": 2043,
//                 "participantId": 3,
//                 "physicalDamageDealt": 53623,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 12308,
//                 "physicalDamageTaken": 15994,
//                 "totalPlayerScore": 0,
//                 "win": false,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 83537,
//                 "neutralMinionsKilledEnemyJungle": 4,
//                 "deaths": 9,
//                 "wardsPlaced": 10,
//                 "perkPrimaryStyle": 8000,
//                 "perkSubStyle": 8200,
//                 "turretKills": 0,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 891,
//                 "goldEarned": 9872,
//                 "killingSprees": 1,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": false,
//                 "champLevel": 13,
//                 "doubleKills": 0,
//                 "inhibitorKills": 0,
//                 "firstInhibitorAssist": false,
//                 "perk0Var1": 771,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 104,
//                 "visionWardsBoughtInGame": 0,
//                 "pentaKills": 0,
//                 "totalHeal": 6669,
//                 "totalMinionsKilled": 21,
//                 "timeCCingOthers": 27
//             },
//             "spell1Id": 4,
//             "participantId": 3,
//             "highestAchievedSeasonTier": "PLATINUM",
//             "spell2Id": 11,
//             "teamId": 100,
//             "timeline": {
//                 "lane": "JUNGLE",
//                 "participantId": 3,
//                 "csDiffPerMinDeltas": {
//                     "0-10": -0.1,
//                     "10-20": -0.7
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 270.8,
//                     "10-20": 386.4
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": 41.099999999999994,
//                     "10-20": -157.99999999999997
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 0,
//                     "10-20": 0.4
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 333.1,
//                     "10-20": 372.9
//                 },
//                 "role": "NONE",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": -125.80000000000001,
//                     "10-20": -302.20000000000005
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 540.1,
//                     "10-20": 888.6
//                 }
//             },
//             "championId": 24
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 4,
//                 "visionScore": 17,
//                 "magicDamageDealtToChampions": 165,
//                 "largestMultiKill": 1,
//                 "totalTimeCrowdControlDealt": 104,
//                 "longestTimeSpentLiving": 517,
//                 "perk1Var1": 1685,
//                 "perk1Var3": 0,
//                 "perk1Var2": 0,
//                 "tripleKills": 0,
//                 "perk5": 8444,
//                 "perk4": 8473,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 5,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 1569,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 8,
//                 "damageDealtToTurrets": 2642,
//                 "physicalDamageDealtToChampions": 21031,
//                 "damageDealtToObjectives": 2642,
//                 "perk2Var2": 40,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 1,
//                 "perk2Var1": 14,
//                 "perk4Var1": 949,
//                 "totalDamageTaken": 36793,
//                 "perk4Var3": 0,
//                 "wardsKilled": 3,
//                 "largestCriticalStrike": 0,
//                 "largestKillingSpree": 4,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 258,
//                 "firstBloodAssist": false,
//                 "item2": 3111,
//                 "item3": 3071,
//                 "item0": 1055,
//                 "item1": 3074,
//                 "item6": 3340,
//                 "item4": 1028,
//                 "item5": 3067,
//                 "perk1": 9111,
//                 "perk0": 8005,
//                 "perk3": 8014,
//                 "perk2": 9104,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 381,
//                 "damageSelfMitigated": 25628,
//                 "magicalDamageTaken": 7858,
//                 "perk0Var2": 2117,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 3905,
//                 "assists": 15,
//                 "perk4Var2": 0,
//                 "goldSpent": 9300,
//                 "trueDamageDealt": 6905,
//                 "participantId": 4,
//                 "physicalDamageDealt": 93715,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 21197,
//                 "physicalDamageTaken": 25028,
//                 "totalPlayerScore": 0,
//                 "win": false,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 100878,
//                 "neutralMinionsKilledEnemyJungle": 0,
//                 "deaths": 7,
//                 "wardsPlaced": 8,
//                 "perkPrimaryStyle": 8000,
//                 "perkSubStyle": 8400,
//                 "turretKills": 1,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 0,
//                 "goldEarned": 10208,
//                 "killingSprees": 1,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": false,
//                 "champLevel": 14,
//                 "doubleKills": 0,
//                 "inhibitorKills": 0,
//                 "firstInhibitorAssist": false,
//                 "perk0Var1": 3322,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 1205,
//                 "visionWardsBoughtInGame": 0,
//                 "pentaKills": 0,
//                 "totalHeal": 1940,
//                 "totalMinionsKilled": 123,
//                 "timeCCingOthers": 10
//             },
//             "spell1Id": 12,
//             "participantId": 4,
//             "highestAchievedSeasonTier": "PLATINUM",
//             "spell2Id": 4,
//             "teamId": 100,
//             "timeline": {
//                 "lane": "TOP",
//                 "participantId": 4,
//                 "csDiffPerMinDeltas": {
//                     "0-10": -1.3000000000000003,
//                     "10-20": 0.8000000000000003
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 258.8,
//                     "10-20": 456
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": -33.69999999999999,
//                     "10-20": 147.30000000000004
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 4.199999999999999,
//                     "10-20": 5.7
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 345.4,
//                     "10-20": 543.2
//                 },
//                 "role": "SOLO",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": -39.30000000000001,
//                     "10-20": 421.4
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 487.5,
//                     "10-20": 1431.6
//                 }
//             },
//             "championId": 240
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 0,
//                 "visionScore": 43,
//                 "magicDamageDealtToChampions": 3880,
//                 "largestMultiKill": 1,
//                 "totalTimeCrowdControlDealt": 67,
//                 "longestTimeSpentLiving": 442,
//                 "perk1Var1": 9,
//                 "perk1Var3": 0,
//                 "perk1Var2": 0,
//                 "tripleKills": 0,
//                 "perk5": 8210,
//                 "perk4": 8224,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 2,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 0,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 4,
//                 "damageDealtToTurrets": 1030,
//                 "physicalDamageDealtToChampions": 225,
//                 "damageDealtToObjectives": 1030,
//                 "perk2Var2": 0,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 4,
//                 "perk2Var1": 4,
//                 "perk4Var1": 673,
//                 "totalDamageTaken": 17814,
//                 "perk4Var3": 0,
//                 "wardsKilled": 6,
//                 "largestCriticalStrike": 0,
//                 "largestKillingSpree": 0,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 7068,
//                 "firstBloodAssist": false,
//                 "item2": 1011,
//                 "item3": 3111,
//                 "item0": 3092,
//                 "item1": 3504,
//                 "item6": 3364,
//                 "item4": 3067,
//                 "item5": 0,
//                 "perk1": 8304,
//                 "perk0": 8326,
//                 "perk3": 8352,
//                 "perk2": 8345,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 101,
//                 "damageSelfMitigated": 16306,
//                 "magicalDamageTaken": 4088,
//                 "perk0Var2": 0,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 1653,
//                 "assists": 11,
//                 "perk4Var2": 0,
//                 "goldSpent": 7125,
//                 "trueDamageDealt": 150,
//                 "participantId": 5,
//                 "physicalDamageDealt": 1996,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 4255,
//                 "physicalDamageTaken": 12072,
//                 "totalPlayerScore": 0,
//                 "win": false,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 9214,
//                 "neutralMinionsKilledEnemyJungle": 0,
//                 "deaths": 6,
//                 "wardsPlaced": 23,
//                 "perkPrimaryStyle": 8300,
//                 "perkSubStyle": 8200,
//                 "turretKills": 0,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 150,
//                 "goldEarned": 7443,
//                 "killingSprees": 0,
//                 "unrealKills": 0,
//                 "firstTowerAssist": true,
//                 "firstTowerKill": false,
//                 "champLevel": 11,
//                 "doubleKills": 0,
//                 "inhibitorKills": 0,
//                 "firstInhibitorAssist": false,
//                 "perk0Var1": 3,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 0,
//                 "visionWardsBoughtInGame": 3,
//                 "pentaKills": 0,
//                 "totalHeal": 3489,
//                 "totalMinionsKilled": 7,
//                 "timeCCingOthers": 16
//             },
//             "spell1Id": 4,
//             "participantId": 5,
//             "highestAchievedSeasonTier": "GOLD",
//             "spell2Id": 14,
//             "teamId": 100,
//             "timeline": {
//                 "lane": "BOTTOM",
//                 "participantId": 5,
//                 "csDiffPerMinDeltas": {
//                     "0-10": -0.25,
//                     "10-20": 0.34999999999999964
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 189.8,
//                     "10-20": 301.6
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": 59.7,
//                     "10-20": -7.149999999999977
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 0,
//                     "10-20": 0.4
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 272.7,
//                     "10-20": 322.4
//                 },
//                 "role": "DUO_SUPPORT",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": -50.89999999999998,
//                     "10-20": 192.10000000000005
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 192.3,
//                     "10-20": 517.6
//                 }
//             },
//             "championId": 497
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 9,
//                 "visionScore": 9,
//                 "magicDamageDealtToChampions": 667,
//                 "largestMultiKill": 1,
//                 "totalTimeCrowdControlDealt": 261,
//                 "longestTimeSpentLiving": 379,
//                 "perk1Var1": 250,
//                 "perk1Var3": 0,
//                 "perk1Var2": 179,
//                 "tripleKills": 0,
//                 "perk5": 8352,
//                 "perk4": 8345,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 5,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 67,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 15,
//                 "damageDealtToTurrets": 6453,
//                 "physicalDamageDealtToChampions": 16770,
//                 "damageDealtToObjectives": 14840,
//                 "perk2Var2": 0,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 4,
//                 "perk2Var1": 0,
//                 "perk4Var1": 4,
//                 "totalDamageTaken": 13574,
//                 "perk4Var3": 0,
//                 "wardsKilled": 1,
//                 "largestCriticalStrike": 942,
//                 "largestKillingSpree": 3,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 11399,
//                 "firstBloodAssist": false,
//                 "item2": 1051,
//                 "item3": 3124,
//                 "item0": 1055,
//                 "item1": 3508,
//                 "item6": 3363,
//                 "item4": 3009,
//                 "item5": 1042,
//                 "perk1": 8226,
//                 "perk0": 8229,
//                 "perk3": 8236,
//                 "perk2": 8210,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 14,
//                 "damageSelfMitigated": 6925,
//                 "magicalDamageTaken": 2969,
//                 "perk0Var2": 0,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 90,
//                 "assists": 10,
//                 "perk4Var2": 0,
//                 "goldSpent": 8900,
//                 "trueDamageDealt": 0,
//                 "participantId": 6,
//                 "physicalDamageDealt": 138521,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 17438,
//                 "physicalDamageTaken": 10514,
//                 "totalPlayerScore": 0,
//                 "win": true,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 149921,
//                 "neutralMinionsKilledEnemyJungle": 0,
//                 "deaths": 5,
//                 "wardsPlaced": 8,
//                 "perkPrimaryStyle": 8200,
//                 "perkSubStyle": 8300,
//                 "turretKills": 1,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 0,
//                 "goldEarned": 11998,
//                 "killingSprees": 1,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": false,
//                 "champLevel": 14,
//                 "doubleKills": 0,
//                 "inhibitorKills": 0,
//                 "firstInhibitorAssist": true,
//                 "perk0Var1": 1523,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 0,
//                 "visionWardsBoughtInGame": 0,
//                 "pentaKills": 0,
//                 "totalHeal": 1794,
//                 "totalMinionsKilled": 177,
//                 "timeCCingOthers": 12
//             },
//             "spell1Id": 4,
//             "participantId": 6,
//             "highestAchievedSeasonTier": "DIAMOND",
//             "spell2Id": 7,
//             "teamId": 200,
//             "timeline": {
//                 "lane": "BOTTOM",
//                 "participantId": 6,
//                 "csDiffPerMinDeltas": {
//                     "0-10": 0.25,
//                     "10-20": -0.34999999999999964
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 250.5,
//                     "10-20": 411.6
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": -59.7,
//                     "10-20": 7.149999999999977
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 6.7,
//                     "10-20": 5.6
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 264.7,
//                     "10-20": 371.79999999999995
//                 },
//                 "role": "DUO_CARRY",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": 50.89999999999998,
//                     "10-20": -192.10000000000005
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 333.3,
//                     "10-20": 495.4
//                 }
//             },
//             "championId": 202
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 71,
//                 "visionScore": 20,
//                 "magicDamageDealtToChampions": 2012,
//                 "largestMultiKill": 2,
//                 "totalTimeCrowdControlDealt": 738,
//                 "longestTimeSpentLiving": 582,
//                 "perk1Var1": 647,
//                 "perk1Var3": 0,
//                 "perk1Var2": 0,
//                 "tripleKills": 0,
//                 "perk5": 8014,
//                 "perk4": 9111,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 13,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 562,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 116,
//                 "damageDealtToTurrets": 7261,
//                 "physicalDamageDealtToChampions": 17015,
//                 "damageDealtToObjectives": 37658,
//                 "perk2Var2": 0,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 1,
//                 "perk2Var1": 18,
//                 "perk4Var1": 3116,
//                 "totalDamageTaken": 32939,
//                 "perk4Var3": 0,
//                 "wardsKilled": 2,
//                 "largestCriticalStrike": 0,
//                 "largestKillingSpree": 8,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 23809,
//                 "firstBloodAssist": false,
//                 "item2": 2031,
//                 "item3": 3047,
//                 "item0": 3748,
//                 "item1": 3143,
//                 "item6": 3340,
//                 "item4": 1413,
//                 "item5": 1011,
//                 "perk1": 8143,
//                 "perk0": 8112,
//                 "perk3": 8105,
//                 "perk2": 8138,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 5,
//                 "damageSelfMitigated": 33116,
//                 "magicalDamageTaken": 4773,
//                 "perk0Var2": 0,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 779,
//                 "assists": 11,
//                 "perk4Var2": 0,
//                 "goldSpent": 11300,
//                 "trueDamageDealt": 18306,
//                 "participantId": 7,
//                 "physicalDamageDealt": 123490,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 20685,
//                 "physicalDamageTaken": 27386,
//                 "totalPlayerScore": 0,
//                 "win": true,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 165606,
//                 "neutralMinionsKilledEnemyJungle": 12,
//                 "deaths": 3,
//                 "wardsPlaced": 12,
//                 "perkPrimaryStyle": 8100,
//                 "perkSubStyle": 8000,
//                 "turretKills": 3,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 1658,
//                 "goldEarned": 14948,
//                 "killingSprees": 2,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": false,
//                 "champLevel": 15,
//                 "doubleKills": 3,
//                 "inhibitorKills": 1,
//                 "firstInhibitorAssist": true,
//                 "perk0Var1": 1717,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 0,
//                 "visionWardsBoughtInGame": 2,
//                 "pentaKills": 0,
//                 "totalHeal": 11354,
//                 "totalMinionsKilled": 28,
//                 "timeCCingOthers": 25
//             },
//             "spell1Id": 4,
//             "participantId": 7,
//             "highestAchievedSeasonTier": "PLATINUM",
//             "spell2Id": 11,
//             "teamId": 200,
//             "timeline": {
//                 "lane": "JUNGLE",
//                 "participantId": 7,
//                 "csDiffPerMinDeltas": {
//                     "0-10": 0.1,
//                     "10-20": 0.7
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 262.20000000000005,
//                     "10-20": 562.9000000000001
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": -41.099999999999994,
//                     "10-20": 157.99999999999997
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 0.1,
//                     "10-20": 1.1
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 292,
//                     "10-20": 530.9
//                 },
//                 "role": "NONE",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": 125.80000000000001,
//                     "10-20": 302.20000000000005
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 665.9,
//                     "10-20": 1190.8000000000002
//                 }
//             },
//             "championId": 59
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 4,
//                 "visionScore": 45,
//                 "magicDamageDealtToChampions": 3726,
//                 "largestMultiKill": 1,
//                 "totalTimeCrowdControlDealt": 153,
//                 "longestTimeSpentLiving": 465,
//                 "perk1Var1": 250,
//                 "perk1Var3": 0,
//                 "perk1Var2": 168,
//                 "tripleKills": 0,
//                 "perk5": 8463,
//                 "perk4": 8453,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 2,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 352,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 8,
//                 "damageDealtToTurrets": 3490,
//                 "physicalDamageDealtToChampions": 688,
//                 "damageDealtToObjectives": 7110,
//                 "perk2Var2": 0,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 6,
//                 "perk2Var1": 24,
//                 "perk4Var1": 264,
//                 "totalDamageTaken": 12071,
//                 "perk4Var3": 0,
//                 "wardsKilled": 3,
//                 "largestCriticalStrike": 0,
//                 "largestKillingSpree": 0,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 16539,
//                 "firstBloodAssist": false,
//                 "item2": 2055,
//                 "item3": 3504,
//                 "item0": 3092,
//                 "item1": 3107,
//                 "item6": 3364,
//                 "item4": 3108,
//                 "item5": 3117,
//                 "perk1": 8226,
//                 "perk0": 8214,
//                 "perk3": 8232,
//                 "perk2": 8234,
//                 "perk3Var3": 0,
//                 "perk3Var2": 40,
//                 "perk3Var1": 2,
//                 "damageSelfMitigated": 6031,
//                 "magicalDamageTaken": 1723,
//                 "perk0Var2": 1272,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 0,
//                 "assists": 17,
//                 "perk4Var2": 861,
//                 "goldSpent": 8800,
//                 "trueDamageDealt": 3604,
//                 "participantId": 8,
//                 "physicalDamageDealt": 5908,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 6134,
//                 "physicalDamageTaken": 10348,
//                 "totalPlayerScore": 0,
//                 "win": true,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 26051,
//                 "neutralMinionsKilledEnemyJungle": 0,
//                 "deaths": 5,
//                 "wardsPlaced": 22,
//                 "perkPrimaryStyle": 8200,
//                 "perkSubStyle": 8400,
//                 "turretKills": 1,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 1720,
//                 "goldEarned": 9524,
//                 "killingSprees": 0,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": false,
//                 "champLevel": 13,
//                 "doubleKills": 0,
//                 "inhibitorKills": 0,
//                 "firstInhibitorAssist": true,
//                 "perk0Var1": 414,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 0,
//                 "visionWardsBoughtInGame": 8,
//                 "pentaKills": 0,
//                 "totalHeal": 2682,
//                 "totalMinionsKilled": 15,
//                 "timeCCingOthers": 11
//             },
//             "spell1Id": 3,
//             "participantId": 8,
//             "highestAchievedSeasonTier": "GOLD",
//             "spell2Id": 4,
//             "teamId": 200,
//             "timeline": {
//                 "lane": "BOTTOM",
//                 "participantId": 8,
//                 "csDiffPerMinDeltas": {
//                     "0-10": 0.25,
//                     "10-20": -0.34999999999999964
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 126.9,
//                     "10-20": 392.9
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": -59.7,
//                     "10-20": 7.149999999999977
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 0.1,
//                     "10-20": 0.9
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 235.3,
//                     "10-20": 386.7
//                 },
//                 "role": "DUO_SUPPORT",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": 50.89999999999998,
//                     "10-20": -192.10000000000005
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 307.4,
//                     "10-20": 320.1
//                 }
//             },
//             "championId": 43
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 0,
//                 "visionScore": 11,
//                 "magicDamageDealtToChampions": 18406,
//                 "largestMultiKill": 1,
//                 "totalTimeCrowdControlDealt": 142,
//                 "longestTimeSpentLiving": 800,
//                 "perk1Var1": 8,
//                 "perk1Var3": 0,
//                 "perk1Var2": 3,
//                 "tripleKills": 0,
//                 "perk5": 8234,
//                 "perk4": 8237,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 6,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 20,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 0,
//                 "damageDealtToTurrets": 2454,
//                 "physicalDamageDealtToChampions": 1873,
//                 "damageDealtToObjectives": 3846,
//                 "perk2Var2": 0,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 2,
//                 "perk2Var1": 1592,
//                 "perk4Var1": 647,
//                 "totalDamageTaken": 16399,
//                 "perk4Var3": 0,
//                 "wardsKilled": 0,
//                 "largestCriticalStrike": 0,
//                 "largestKillingSpree": 4,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 79180,
//                 "firstBloodAssist": false,
//                 "item2": 3285,
//                 "item3": 1056,
//                 "item0": 3157,
//                 "item1": 1026,
//                 "item6": 3364,
//                 "item4": 1052,
//                 "item5": 2422,
//                 "perk1": 8304,
//                 "perk0": 8326,
//                 "perk3": 8347,
//                 "perk2": 8316,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 0,
//                 "damageSelfMitigated": 9819,
//                 "magicalDamageTaken": 2987,
//                 "perk0Var2": 0,
//                 "firstInhibitorKill": true,
//                 "trueDamageTaken": 631,
//                 "assists": 11,
//                 "perk4Var2": 0,
//                 "goldSpent": 8185,
//                 "trueDamageDealt": 128658,
//                 "participantId": 9,
//                 "physicalDamageDealt": 11084,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 23252,
//                 "physicalDamageTaken": 12780,
//                 "totalPlayerScore": 0,
//                 "win": true,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 218922,
//                 "neutralMinionsKilledEnemyJungle": 0,
//                 "deaths": 5,
//                 "wardsPlaced": 8,
//                 "perkPrimaryStyle": 8300,
//                 "perkSubStyle": 8200,
//                 "turretKills": 2,
//                 "firstBloodKill": false,
//                 "trueDamageDealtToChampions": 2973,
//                 "goldEarned": 11138,
//                 "killingSprees": 1,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": false,
//                 "champLevel": 15,
//                 "doubleKills": 0,
//                 "inhibitorKills": 2,
//                 "firstInhibitorAssist": false,
//                 "perk0Var1": 1,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 0,
//                 "visionWardsBoughtInGame": 0,
//                 "pentaKills": 0,
//                 "totalHeal": 1900,
//                 "totalMinionsKilled": 142,
//                 "timeCCingOthers": 36
//             },
//             "spell1Id": 4,
//             "participantId": 9,
//             "highestAchievedSeasonTier": "PLATINUM",
//             "spell2Id": 7,
//             "teamId": 200,
//             "timeline": {
//                 "lane": "MIDDLE",
//                 "participantId": 9,
//                 "csDiffPerMinDeltas": {
//                     "0-10": 1.1000000000000005,
//                     "10-20": -1.0000000000000002
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 320.79999999999995,
//                     "10-20": 383.70000000000005
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": 177.20000000000002,
//                     "10-20": -19.80000000000001
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 6.9,
//                     "10-20": 4.6
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 499.1,
//                     "10-20": 377.5
//                 },
//                 "role": "SOLO",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": -103.90000000000002,
//                     "10-20": 34.400000000000006
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 382.2,
//                     "10-20": 583.1
//                 }
//             },
//             "championId": 142
//         },
//         {
//             "stats": {
//                 "neutralMinionsKilledTeamJungle": 0,
//                 "visionScore": 18,
//                 "magicDamageDealtToChampions": 6042,
//                 "largestMultiKill": 2,
//                 "totalTimeCrowdControlDealt": 87,
//                 "longestTimeSpentLiving": 394,
//                 "perk1Var1": 883,
//                 "perk1Var3": 0,
//                 "perk1Var2": 0,
//                 "tripleKills": 0,
//                 "perk5": 8138,
//                 "perk4": 8143,
//                 "playerScore9": 0,
//                 "playerScore8": 0,
//                 "kills": 10,
//                 "playerScore1": 0,
//                 "playerScore0": 0,
//                 "playerScore3": 0,
//                 "playerScore2": 0,
//                 "playerScore5": 0,
//                 "playerScore4": 0,
//                 "playerScore7": 0,
//                 "playerScore6": 0,
//                 "perk5Var1": 18,
//                 "perk5Var3": 0,
//                 "perk5Var2": 0,
//                 "totalScoreRank": 0,
//                 "neutralMinionsKilled": 0,
//                 "damageDealtToTurrets": 2932,
//                 "physicalDamageDealtToChampions": 14369,
//                 "damageDealtToObjectives": 7979,
//                 "perk2Var2": 50,
//                 "perk2Var3": 0,
//                 "totalUnitsHealed": 1,
//                 "perk2Var1": 13,
//                 "perk4Var1": 953,
//                 "totalDamageTaken": 26581,
//                 "perk4Var3": 0,
//                 "wardsKilled": 1,
//                 "largestCriticalStrike": 0,
//                 "largestKillingSpree": 3,
//                 "quadraKills": 0,
//                 "magicDamageDealt": 15173,
//                 "firstBloodAssist": false,
//                 "item2": 3047,
//                 "item3": 3143,
//                 "item0": 2033,
//                 "item1": 3078,
//                 "item6": 3340,
//                 "item4": 0,
//                 "item5": 3153,
//                 "perk1": 9111,
//                 "perk0": 8010,
//                 "perk3": 8014,
//                 "perk2": 9104,
//                 "perk3Var3": 0,
//                 "perk3Var2": 0,
//                 "perk3Var1": 617,
//                 "damageSelfMitigated": 20081,
//                 "magicalDamageTaken": 3183,
//                 "perk0Var2": 0,
//                 "firstInhibitorKill": false,
//                 "trueDamageTaken": 238,
//                 "assists": 7,
//                 "perk4Var2": 0,
//                 "goldSpent": 11708,
//                 "trueDamageDealt": 36638,
//                 "participantId": 10,
//                 "physicalDamageDealt": 69202,
//                 "sightWardsBoughtInGame": 0,
//                 "totalDamageDealtToChampions": 22850,
//                 "physicalDamageTaken": 23160,
//                 "totalPlayerScore": 0,
//                 "win": true,
//                 "objectivePlayerScore": 0,
//                 "totalDamageDealt": 121014,
//                 "neutralMinionsKilledEnemyJungle": 0,
//                 "deaths": 10,
//                 "wardsPlaced": 12,
//                 "perkPrimaryStyle": 8000,
//                 "perkSubStyle": 8100,
//                 "turretKills": 1,
//                 "firstBloodKill": true,
//                 "trueDamageDealtToChampions": 2438,
//                 "goldEarned": 12199,
//                 "killingSprees": 3,
//                 "unrealKills": 0,
//                 "firstTowerAssist": false,
//                 "firstTowerKill": false,
//                 "champLevel": 14,
//                 "doubleKills": 1,
//                 "inhibitorKills": 0,
//                 "firstInhibitorAssist": true,
//                 "perk0Var1": 957,
//                 "combatPlayerScore": 0,
//                 "perk0Var3": 0,
//                 "visionWardsBoughtInGame": 1,
//                 "pentaKills": 0,
//                 "totalHeal": 3174,
//                 "totalMinionsKilled": 118,
//                 "timeCCingOthers": 20
//             },
//             "spell1Id": 4,
//             "participantId": 10,
//             "highestAchievedSeasonTier": "UNRANKED",
//             "spell2Id": 12,
//             "teamId": 200,
//             "timeline": {
//                 "lane": "TOP",
//                 "participantId": 10,
//                 "csDiffPerMinDeltas": {
//                     "0-10": 1.3000000000000003,
//                     "10-20": -0.8000000000000003
//                 },
//                 "goldPerMinDeltas": {
//                     "0-10": 312.5,
//                     "10-20": 442.4
//                 },
//                 "xpDiffPerMinDeltas": {
//                     "0-10": 33.69999999999999,
//                     "10-20": -147.30000000000004
//                 },
//                 "creepsPerMinDeltas": {
//                     "0-10": 5.5,
//                     "10-20": 4.9
//                 },
//                 "xpPerMinDeltas": {
//                     "0-10": 379.1,
//                     "10-20": 395.9
//                 },
//                 "role": "SOLO",
//                 "damageTakenDiffPerMinDeltas": {
//                     "0-10": 39.30000000000001,
//                     "10-20": -421.4
//                 },
//                 "damageTakenPerMinDeltas": {
//                     "0-10": 526.8,
//                     "10-20": 1010.2
//                 }
//             },
//             "championId": 39
//         }
//     ],
//     "gameDuration": 1652,
//     "gameCreation": 1523211023066
// }
